### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Firesphere** [docmarionum1/slack-archive-bot#16]
Hey,

I just wanted to thank you for your initial work. I've used your initial work to build a Slack Archive Bot, slightly more complex than yours. You can view the source here:
https://bitbucket.org/SimonErkelens/stripeslackbot-2/src/338a2b507c4d0899efc4f38eb20764945a094df7/slackbot/?at=master

It's combined with a SilverStripe website frontend that allows for logging in with Slack, a Solr powered search and some features like when using @botname, the bot will reply with the first search result, and a link to more search results on the website.

Thanks! 🙇‍♂️🙇‍♂️

**Comment by docmarionum1** [comment]
That's cool. I'm glad you found it useful :)

**Comment by l3oxy** [comment]
@Firesphere , when attempting to access that page, it says Access Denied.
Is there any way to access it?
