### ISSUE TITLE
Evaluating this - Does it store attachments/images url's etc? 

### ISSUE THREAD

**Issue by wolfen351** [docmarionum1/slack-archive-bot#17]
Just wondering:

* Does it store any uploaded files?
* Does it store images?
* Does it store url's?

If it does, how to search them?

**Comment by docmarionum1** [comment]
It stores the url text itself, but not any preview of it. 

It doesn't store images or files. What it could do with only minor modification, would be to store the slack link to images and files so that they can be retrieved.

**Comment by docmarionum1** [comment]
I created #18 to track support of that.
