### ISSUE TITLE
Import fails silently upon permission denied

### ISSUE THREAD

**Issue by tobast** [docmarionum1/slack-archive-bot#24]
Hello,

When trying to import a slack export on which `slack-archive-bot` has no permission, the import fails silently: the `glob.glob` finds no file matching `*.json` for each channel, and the archive bot thus imports the content of zero files.

**Comment by docmarionum1** [comment]
If the import has no permission on the entire folder, it should fail trying to load `channels.json`.

But I've added an additional warning when it can't find any messages for any particular channel.

https://github.com/docmarionum1/slack-archive-bot/commit/f04a6bbce45f81e335c8fb6206dbec2aa867d7f2
