### ISSUE TITLE
Update for Python 3 and slackclient 2

### ISSUE THREAD

**Issue by mattbk** [docmarionum1/slack-archive-bot#27]
See https://github.com/slackapi/python-slackclient/issues/183#issuecomment-518425323.

> Oh, it seems you're using the old version of the package now. That is, for some reason you have v1 installed. In v1, the module was also named slackclient and featured a class named SlackClient. In v2, the module name changed to slack, (but the package is still named slackclient) and the client was split into WebClient and RtmClient.

**Comment by mattbk** [comment]
Oh, I see, this project is using Python 2.7?

**Comment by mattbk** [comment]
I may take a try at this, but the reason is that it seems like you can't create "Classic Apps" anymore (after Feb 21 2020).

**Comment by docmarionum1** [comment]
Addressed by #30
