### ISSUE TITLE
Will slack-archive-bot be updated for Slack's Conversations API?

### ISSUE THREAD

**Issue by alboss** [docmarionum1/slack-archive-bot#29]
I've been getting messages from Slack, saying on Feb. 24, 2021 they'll end support for the legacy methods that slack-archive-bot uses. Are there plans to update it? I've come to depend on it and if the plug is about to be pulled I'd best start looking for another solution--if there even is one.

**Comment by docmarionum1** [comment]
I don't have plans to update this at the moment since I'm not actively using it myself. 

Does anyone know of good alternatives? Or @alboss  if you find one let me know. I can work on ETL for bringing data from slack-archive-bot over to a new system. 

It looks like it might be a big lift to get it up-to-date but if there aren't any good alternatives, I can take a look into doing this before Feb 24.

**Comment by docmarionum1** [comment]
@alboss Would you be able to test the new version from #30?

**Comment by alboss** [comment]
Absolutely! Sorry for the radio silence; I was having to fight some hardware issues this last week.

**Comment by dyss1992** [comment]
> @alboss Would you be able to test the new version from #30?

Thanks for your work. I follow the instructions, and I'm on Step 5, got this error:


> DEBUG:slack_sdk.web.base_client:Sending a request - url: https://www.slack.com/api/conversations.members, query_params: {}, body_params: {'channel': 'C3ZPVHBGR'}, files: {}, json_body: None, headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': '(redacted)', 'User-Agent': 'Bolt/1.2.1 Python/3.8.5 slackclient/3.2.0 Darwin/20.2.0'}
> DEBUG:slack_sdk.web.slack_response:Received the following response - status: 200, headers: {'date': 'Tue, 26 Jan 2021 17:52:17 GMT', 'server': 'Apache', 'x-xss-protection': '0', 'pragma': 'no-cache', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-slack-req-id': '9bd2c06303a6d87e5c3613a7469d86ba', 'x-content-type-options': 'nosniff', 'referrer-policy': 'no-referrer', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'x-slack-backend': 'r', 'x-oauth-scopes': 'channels:history,channels:read,chat:write,im:history,im:read,users:read,groups:history,groups:read', 'x-accepted-oauth-scopes': 'channels:read,groups:read,mpim:read,im:read,read', 'expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'vary': 'Accept-Encoding', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'content-type': 'application/json; charset=utf-8', 'x-envoy-upstream-service-time': '15', 'x-backend': 'main_normal main_canary_with_overflow main_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-tjrn', 'x-via': 'envoy-www-iad-c1oo, haproxy-edge-nrt-74j5', 'x-slack-shared-secret-outcome': 'shared-secret', 'via': 'envoy-www-iad-c1oo', 'connection': 'close', 'transfer-encoding': 'chunked'}, body: {'ok': False, 'error': 'fetch_members_failed', 'response_metadata': {'messages': ['[ERROR] Failed to fetch members for the channel.']}}

> Traceback (most recent call last):
>   File "archivebot.py", line 339, in <module>
>     main()
>   File "archivebot.py", line 333, in main
>     update_channels(conn, cursor)
>   File "archivebot.py", line 93, in update_channels
>     channel_id, channel_name, channel_is_private, members = get_channel_info(
>   File "archivebot.py", line 70, in get_channel_info
>     response = app.client.conversations_members(channel=channel["id"])
>   File "/Users/zhangyangfan/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/client.py", line 1233, in conversations_members
>     return self.api_call("conversations.members", http_verb="GET", params=kwargs)
>   File "/Users/zhangyangfan/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 127, in api_call
>     return self._sync_send(api_url=api_url, req_args=req_args)
>   File "/Users/zhangyangfan/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 163, in _sync_send
>     return self._urllib_api_call(
>   File "/Users/zhangyangfan/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 291, in _urllib_api_call
>     return SlackResponse(
>   File "/Users/zhangyangfan/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/slack_response.py", line 201, in validate
>     raise e.SlackApiError(message=msg, response=self)

> slack_sdk.errors.SlackApiError: The request to the Slack API failed.
> The server responded with: {'ok': False, 'error': 'fetch_members_failed', 'response_metadata': {'messages': ['[ERROR] Failed to fetch members for the channel.']}}

If you need any info, pls tell me.

**Comment by alboss** [comment]
I had what looks like the same results as @dyss1992, also on step 5 of the instructions.  

> ERROR] Failed to fetch members for the channel.']}}
> Traceback (most recent call last):
>   File "archivebot.py", line 339, in <module>
>     main()
>   File "archivebot.py", line 333, in main
>     update_channels(conn, cursor)
>   File "archivebot.py", line 93, in update_channels
>     channel_id, channel_name, channel_is_private, members = get_channel_info(
>   File "archivebot.py", line 70, in get_channel_info
>     response = app.client.conversations_members(channel=channel["id"])
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slack_sdk/web/client.py", line 1233, in conversations_members
>     return self.api_call("conversations.members", http_verb="GET", params=kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 127, in api_call
>     return self._sync_send(api_url=api_url, req_args=req_args)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 163, in _sync_send
>     return self._urllib_api_call(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 291, in _urllib_api_call
>     return SlackResponse(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slack_sdk/web/slack_response.py", line 201, in validate
>     raise e.SlackApiError(message=msg, response=self)
> slack_sdk.errors.SlackApiError: The request to the Slack API failed.
> The server responded with: {'ok': False, 'error': 'fetch_members_failed', 'response_metadata': {'messages': ['[ERROR] Failed to fetch members for the channel.']}}

**Comment by docmarionum1** [comment]
@dyss1992 Is the bot a member of that channel (C3ZPVHBGR) or any other channels yet? 

Do you see any successful responses to `conversations.members` or does this fail on the first request?

I haven't encountered this issue and can't replicate it on my end. Your permissions look correct. 

Going on the theory that it's a problem with the bot membership, I've pushed a change to the `conversations-api` branch. Let me know if that fixes the issue.

cc @alboss

**Comment by dyss1992** [comment]
> @dyss1992 Is the bot a member of that channel (C3ZPVHBGR) or any other channels yet?
> 
> Do you see any successful responses to `conversations.members` or does this fail on the first request?
> 
> I haven't encountered this issue and can't replicate it on my end. Your permissions look correct.
> 
> Going on the theory that it's a problem with the bot membership, I've pushed a change to the `conversations-api` branch. Let me know if that fixes the issue.
> 
> cc @alboss

Yes, I have invited the bot to all my channel. And I pull the latest version, there is no longer error like before.

but I it still not working fine, with follow log loop:

> DEBUG:slack_sdk.web.slack_response:Received the following response - status: 200, headers: {'date': 'Thu, 28 Jan 2021 16:07:02 GMT', 'server': 'Apache', 'x-xss-protection': '0', 'pragma': 'no-cache', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-slack-req-id': 'b12e1db28e6015d2b96572563315f946', 'x-content-type-options': 'nosniff', 'referrer-policy': 'no-referrer', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'x-slack-backend': 'r', 'x-oauth-scopes': 'channels:history,channels:read,chat:write,im:history,im:read,users:read,groups:history,groups:read', 'x-accepted-oauth-scopes': 'channels:read,groups:read,mpim:read,im:read,read', 'expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'vary': 'Accept-Encoding', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'content-type': 'application/json; charset=utf-8', 'x-envoy-upstream-service-time': '17', 'x-backend': 'main_normal main_canary_with_overflow main_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-hwu5', 'x-via': 'envoy-www-iad-a43n, haproxy-edge-nrt-zq8h', 'x-slack-shared-secret-outcome': 'shared-secret', 'via': 'envoy-www-iad-a43n', 'connection': 'close', 'transfer-encoding': 'chunked'}, body: {'ok': True, 'members': ['U3ZQ7C8NM', 'U408FEB5W', 'U408ZMB8Q', 'U409JHJE4', 'U40CCV6D9', 'U40DZHZ5X', 'U40E1AHMF', 'U40HV2S3A', 'U40UE2YPL', 'U40V33GPL', 'U410535R9', 'U412MAPPD', 'U41342FQU', 'U416W0YKW', 'U417LN0SZ', 'U4189MLSH', 'U41AK6DL0', 'U41K49Z9S', 'U41KUP147', 'U41L7142K', 'U41L89E78', 'U41P5SS07', 'U41QNEZM5', 'U41R7GKNK', 'U41UTGQ4D', 'U4265F4A0', 'U42AZSRMW', 'U43K32HH7', 'U43KPKG58', 'U43LUL3MF', 'U43P68YP8', 'U43TNR5KQ', 'U442CJ8K1', 'U448MP6MS', 'U44AW1CPQ', 'U44C0RJ0G', 'U44C6DBCZ', 'U44CYM2NM', 'U44D7RHMX', 'U44EK7QTA', 'U44EVP58R', 'U44J1G32M', 'U44RV338X', 'U44S71T6J', 'U44U0MD4G', 'U450UD1DZ', 'U4511TPJ5', 'U45136WSF', 'U452V6MM0', 'U455GBL4V', 'U4560M1E3', 'U45AF92QZ', 'U45FW364T', 'U45HWFQ1Y', 'U45LSAWAG', 'U45LWP9GS', 'U45U1L6T1', 'U45V6U9LN', 'U45VCDYDD', 'U4618FGB0', 'U469D5VQE', 'U469K9VAA', 'U4DN2HMDJ', 'U4EHDPN64', 'U4KRWUZ32', 'U4L35DTLY', 'U4L5HJ5PS', 'U4LC3J1N1', 'U4LF4JDM2', 'U4LFFEXNG', 'U4LFG5CUU', 'U4LGCGG1F', 'U4LL80V6Y', 'U4LN12ATA', 'U4M3RKKBJ', 'U4M4BMPCH', 'U4M5TUZA6', 'U4M8S4UTH', 'U4M8TEU2H', 'U4M9AEYEA', 'U4MAAHJGL', 'U4MBCKKA8', 'U4MS9T6PQ', 'U4MSPBAUW', 'U4MUPD90X', 'U4R9T4L3D', 'U4RTV4QVD', 'U4V75EB3M', 'U4X2YBDBK', 'U502TKQ3F', 'U50325JAJ', 'U5MLVVC6N', 'U5P5ZN5UL', 'U5P7BE9T6', 'U5QJB2N23', 'U5YHDUGBA', 'U63JBQ57D', 'U66SJGYF6', 'U6L9PPNSV', 'U703SDT32'], 'response_metadata': {'next_cursor': 'dXNlcl9pZDoyMzgxMzI2MjAxNzY='}}
> DEBUG:slack_sdk.web.base_client:Sending a request - url: https://www.slack.com/api/conversations.members, query_params: {}, body_params: {'channel': 'C40CCV81H'}, files: {}, json_body: None, headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': '(redacted)', 'User-Agent': 'Bolt/1.2.1 Python/3.8.5 slackclient/3.2.0 Darwin/20.2.0'}

**Comment by docmarionum1** [comment]
@dyss1992 I fixed a bug with pagination for that request. Can you pull and give it another go?

**Comment by dyss1992** [comment]
> @dyss1992 I fixed a bug with pagination for that request. Can you pull and give it another go?

Now it can show the message below:
> INFO:__main__:⚡️ Bolt app is running! (development server)

But I send the message to the bot, there is no reply.

**Comment by alboss** [comment]
I suspect this might be user error on my part, but here's where I am after the last two pulls:

Slack bot launches fine. INFO:__main__:⚡️ Bolt app is running! (development server)
Launch Apache serving the code on port 3333
localhost:3333 returns the file index as expected
ngrok http 3333
The ngrok url returns the file index as expected

All good till now. 

However, when I put the url generated by ngrok into the Event Subscriptions, my luck runs out:

> Your request URL didn’t respond with the correct challenge value...
> 
> Request URL Your URL didn't respond with the value of the challenge parameter.

From the ngrok terminal window:

<pre>Connections                   ttl     opn     rt1     rt5     p50     p90           
                              2       0       0.00    0.00    5.28    5.56          
                                                                                    
HTTP Requests                                                                       
-------------                                                                       
                                                                                    
POST /                         200 OK                                        
GET  /favicon.ico              200 OK                                               
GET  /                         200 OK
</pre>
                                              
From the ngrok terminal window I can see that the event subscription is hitting the server on my computer, but the expected response isn't happening.

I'm stumped.

**Comment by docmarionum1** [comment]
@alboss Oh, I think maybe you're not pointing to the correct url. It should be `<ngrok-url>/slack/events`. I'll update the README to be more specific. 

@dyss1992 Similar - did you set up the event subscriptions and did slack say it was correct?

**Comment by dyss1992** [comment]
> @alboss Oh, I think maybe you're not pointing to the correct url. It should be `<ngrok-url>/slack/events`. I'll update the README to be more specific.
> 
> @dyss1992 Similar - did you set up the event subscriptions and did slack say it was correct?

It works! Thank you for your time and patience.

**Comment by alboss** [comment]
**Success!** I'd found the documentation for adding /slack/events at the end of the ngrok url yesterday, but by habit I added a trailing slash and that messed things up.

So, URL validated, and bot events successfully added and saved. I have the bot running in a terminal window and I can see it processing as traffic gets posted in Slack.

Queries are getting results.

Now I just have to figure out a permanent solution for the server so I'm not having to worry about ngrok. Too bad my son no longer has that blade server running in his closet.

**Comment by docmarionum1** [comment]
Great! Thank you both for testing. Let me know if you encounter any other issues.

**Comment by docmarionum1** [comment]
Addressed with #30
