### ISSUE TITLE
Not meeting the challenge (Running via cpanel)

### ISSUE THREAD

**Issue by alboss** [docmarionum1/slack-archive-bot#31]
http://sisypheans.org/slack-archive-bot/slack/events should return an answer to the Slack event challenge, but no such luck. I'm stymied. Any thoughts?

**Comment by alboss** [comment]
Progress but not completion. I have to launch via cPanel, which I'm not familiar with. 

I have a passenger_wsgi.py file that has this:

```
import os
import sys

# activate Python 3
os.system(". bin/activate")

from archivebot.py import App as application
```

But, the application itself, at http://sisypheans.org/slack-archive-bot/, won't start. I think it's expecting a shell launch instead. It's giving me a `stdin: is not a tty` message, and later on a syntax error.

```
stdin: is not a tty
Traceback (most recent call last):
  File "/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 369, in <module>
    app_module = load_app()
  File "/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 76, in load_app
    return imp.load_source('passenger_wsgi', startup_file)
  File "/home/sisyed79/public_html/slack-archive-bot/passenger_wsgi.py", line 13, in <module>
    from archivebot.py import App as application
  File "/home/sisyed79/public_html/slack-archive-bot/archivebot.py", line 178
    """
      ^
SyntaxError: invalid syntax
```

**Comment by alboss** [comment]
Further investigation: the stdin message is only a warning, so for now I'm ignoring it.
The syntax error is bizarre. It doesn't like the closure to the multiline comment.
I moved the multiline comment to its own lines (above `query = f` instead of immediately following the `f`)

Now I have a new error and I'm not sure if I'm making things worse or better, so I'm going to let you guys have a look.

```
stdin: is not a tty
Traceback (most recent call last):
  File "/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 369, in <module>
    app_module = load_app()
  File "/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 76, in load_app
    return imp.load_source('passenger_wsgi', startup_file)
  File "/home/sisyed79/public_html/slack-archive-bot/passenger_wsgi.py", line 12, in <module>
    from archivebot.py import App as application
  File "/home/sisyed79/public_html/slack-archive-bot/archivebot.py", line 6, in <module>
    from slack_bolt import App
  File "/home/sisyed79/.local/lib/python2.7/site-packages/slack_bolt/__init__.py", line 2, in <module>
    from .app import App  # noqa
  File "/home/sisyed79/.local/lib/python2.7/site-packages/slack_bolt/app/__init__.py", line 2, in <module>
    from .app import App  # type: ignore
  File "/home/sisyed79/.local/lib/python2.7/site-packages/slack_bolt/app/app.py", line 71
    *,
     ^
SyntaxError: invalid syntax

```

**Comment by docmarionum1** [comment]
`from archivebot.py import App as application`

This is just the raw App from the bolt library (`from slack_bolt import App`), not the archive bot app.

I'm not familiar with what you're doing, but this looks promising: https://slack.dev/bolt-python/concepts#adapters

You could `from archivebot.py import app` and use it as in the example.

**Comment by matthewlee626** [comment]
Also having trouble with this issue. Not sure where to start, but will be following this thread.

**Comment by alboss** [comment]
WSGI requires a callable object. Are any of the objects callable on their own? 

I took a wild guess and tried using app.start(port=80) and got a permission error.

**Comment by docmarionum1** [comment]
Try this?

```
# Import and initialize archivebot
from archivebot import database_path, db_connect, migrate_db, update_users, update_channels, app

# Copied these from archivebot.main to setup the DB
conn, cursor = db_connect(database_path)
migrate_db(conn, cursor)

# Update the users and channels in the DB and in the local memory mapping
update_users(conn, cursor)
update_channels(conn, cursor)


# Initialize Flask app
from flask import Flask, request
flask_app = Flask(__name__)

# SlackRequestHandler translates WSGI requests to Bolt's interface
# and builds WSGI response from Bolt's response.
from slack_bolt.adapter.flask import SlackRequestHandler
handler = SlackRequestHandler(app)

# Register routes to Flask app
@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    # handler runs App's dispatch method
    return handler.handle(request)
```

**Comment by alboss** [comment]
Try it as a separate python file that’s what the wsgi calls as application?

**Comment by docmarionum1** [comment]
Yeah, make that as a file and in `passenfer_wsgi.py` import `flask_app as application`

**Comment by alboss** [comment]
Ugh.

From http://sisypheans.org/slackbot/slack/events (or even http://sisypheans.org/slackbot/)

```
**Not Found**
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again
```

From the log, I don't think the application is launching:

```
App 14144 output: stdin: is not a tty

App 14144 output:
/opt/passenger-5.3.7-13.el7.cloudlinux/src/helper-scripts/wsgi-loader.py:26:
DeprecationWarning: the imp module is deprecated in favour of importlib;
see the module's documentation for alternative uses

App 14144 output: import sys, os, io, re, imp, threading, signal,
traceback, socket, select, struct, logging, errno
```


Current setup in cPanel:

<img width="948" alt="cPanel_-_Python" src="https://user-images.githubusercontent.com/2267907/109405764-d1c60380-7928-11eb-884d-58ab8108bd07.png">

**Comment by alboss** [comment]
This is just a wild guess, but based on that log, I think that the application startup file needs to be archivebot.py and I just need an entry point that I can call from the passenger wsgi file. In theory, it would be a callable item that returned /slack/events, if I'm understanding this wsgi documentation right.

**Comment by alboss** [comment]
If I leave out `from archivebot import app` then the flaskapp.py file does attempt to run. Of course, it doesn't get very far:
```
App 1815 output: handler = SlackRequestHandler(app)
App 1815 output: NameError: name 'app' is not defined
```
but at least it goes *somewhere*.

**Comment by docmarionum1** [comment]
What happens when you do include `from archivebot import app` Is there an error thrown?

**Comment by alboss** [comment]
There's no error showing in the logs if `from archivebot import app` is there. The log just contains this:
```
App output:
/opt/passenger-5.3.7-13.el7.cloudlinux/src/helper-scripts/wsgi-loader.py:26:
DeprecationWarning: the imp module is deprecated in favour of importlib;
see the module's documentation for alternative uses
App output: import sys, os, io, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
```
So, it seems to pull in the wsgi loader, and then everything stalls.

There's something it doesn't like about pulling in the app but it's not running far enough for the logs to give me any clue.

**Comment by alboss** [comment]
Good news, I think.

I added back the app import and did the following:

In the wsgi file, I added an os.system call that launches the virtual machine and then runs signing_secret bot_token archivebot.py and I can see in the log everything running... until it hits the point where it binds to the port. The problem is not the fault of the script; I can't figure out how, in CPanel, to set the port to anything other than the default of port 80. 

A port below 1024 won't bind for an unprivileged user, so setting the port to 80 isn't going to work even if I wanted it to: it'll throw a permission error. (Yes, I did check.)

So, now I'm waiting on a sysadmin to tell me if they'll change the default port for the archivebot for me. 

I have to say, I'm not exactly enamored of CPanel right now. It keeps getting in my way!

**Comment by alboss** [comment]
With the script set to port 3333 but the server serving it on port 80, hitting the URL does activate the script. The log is looking good:
`INFO:__main__:⚡️ Bolt app is running! `

Of course, the port mismatch means the browser returns an application error, but it's nice to see the log saying that archivebot is running even if I can't reach it.

Also, I'm guessing that hitting this page more than once will get me an error along the lines of the address already being in use. I assume adding `lsof -t -i tcp:3333 | xargs kill -9` to the launch string would prevent that, but this whole thing is feeling like I'm going about it all wrong and I don't want to pile onto that if there's a better way.

**Comment by alboss** [comment]
And the answer is... **Don't use my ISP for this!** Don't get me wrong; they're awesome people--it's just that their setup isn't what I need. They suggested I use a droplet from DigitalOcean, and ten dollars after that I had the bot running in about 5 minutes. Success!

Once again, my sincere thanks to everyone on this project.

**Comment by docmarionum1** [comment]
Glad you got it working! Sorry I couldn't have been more help. Was it an issue specifically with your ISP or cpanel in general?

**Comment by alboss** [comment]
Jeremy, you have been helpful and patient and didn't make me feel like an
idiot. I couldn't ask for better.

My ISP is fairly bare-bones. I think CPanel has got a gazillion different
modules that an ISP can configure, depending on how complex they feel like
being and how much tech support they want to offer when people invariably
mess something up because they had too much power. In this case, the ISP
only offers the one interface, so you have to redo some of the code to get
it to work with wsgi, you had to launch a virtual machine to run Python 3
because their default is still Python 2, and basically fight the
infrastructure every step of the way. Their tech support was very nice but
this was way beyond what they signed up for and they kept telling me to ask
the vendor about stuff that was about their infrastructure and the bot.

I'm incredibly stubborn and I know how Google works, so I got everything
working on my own (eventually) except for the Apache port. I didn't have
access to the config to open a port or to even see what ports higher than
1024 were available. When I asked, that's when they just said, "You know
what? Try this instead." Talk about a night and day difference. Installing
on a service that is set up to do exactly what I needed was so easy that it
has me regretting not doing that in the first place, although it was good
to do some actual Python work for a while.
