### ISSUE TITLE
Not logging threaded replies which are also sent to channel

### ISSUE THREAD

**Issue by fierevere** [docmarionum1/slack-archive-bot#32]
Since moving to conversations api
slack-archive-bot is not logging replies to theads which are also sent to channel.
Plain channel replies are logged, threaded - logged too, but if someone replies in thread and also sends to channel - those messages do not logged, therefore cannot be searched or exported from sqlite database.

**Comment by docmarionum1** [comment]
Thanks for catching that. Should be fixed by #35. Let me know if that doesn't work for you.

**Comment by fierevere** [comment]
Now it works.
Thank you.
