### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Firesphere** [docmarionum1/slack-archive-bot#8]
I can't find any installation instructions, am I looking in the wrong place?
I'm looking to set this up on a Raspberry Pi.

**Comment by docmarionum1** [comment]
See: https://github.com/docmarionum1/slack-archive-bot#installation

Is that sufficient?

**Comment by Firesphere** [comment]
Yes, that works and I'm an idiot for overlooking that  🤦‍♂️
